### ISSUE TITLE
getatoms does not work on ppc

### ISSUE THREAD

**Issue by asarubbo** [kensington/bugbot#16]
```
# python /root/getatoms.py -a ppc --stablereq --no-depends --all-bugs
Traceback (most recent call last):
  File "/root/getatoms.py", line 210, in <module>
    sys.exit(main())
  File "/root/getatoms.py", line 130, in main
    all_attachments = xmlrpc.client.ServerProxy('https://bugs.gentoo.org/xmlrpc.cgi').Bug.attachments({'ids': [ x['id'] for x in bugs ] })['bugs']
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1105, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1445, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1160, in single_request
    resp = http_conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1227, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 356, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
```

**Comment by asarubbo** [comment]
python-3.4.5

**Comment by kensington** [comment]
Checking...

**Comment by kensington** [comment]
According to the python [docs](https://docs.python.org/3/library/http.client.html#http.client.BadStatusLine), an invalid response was received from the server.

**Comment by kensington** [comment]
I think this was an intermittent server error. Please reopen if this persists.
